version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: feedback-postgres
    environment:
      POSTGRES_DB: feedbackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/V1__create_feedbacks_table.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.5
    container_name: feedback-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs,ses,logs
      DEFAULT_REGION: us-east-1
      DEBUG: 0
    volumes:
      - localstack_data:/var/lib/localstack
      - ./infrastructure/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  localstack_data:
