quarkus.lambda.handler=processor-handler

quarkus.sqs.aws.region=${AWS_REGION:us-east-1}
quarkus.sqs.aws.credentials.type=default

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:feedbackdb}
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=5

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

app.sqs.notification-queue-url=${NOTIFICATION_QUEUE_URL}

quarkus.log.level=INFO
quarkus.log.category."br.com.fiap".level=DEBUG

%dev.quarkus.sqs.endpoint-override=http://localhost:4566
%dev.app.sqs.notification-queue-url=http://localhost:4566/000000000000/notification-queue.fifo
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/feedbackdb
