quarkus.lambda.handler=notification-handler

quarkus.ses.aws.region=${AWS_REGION:us-east-1}
quarkus.ses.aws.credentials.type=default

app.admin.email=${ADMIN_EMAIL}
app.ses.sender-email=${SES_SENDER_EMAIL}

quarkus.log.level=INFO
quarkus.log.category."br.com.fiap".level=DEBUG

%dev.quarkus.ses.endpoint-override=http://localhost:4566
%dev.app.admin.email=admin@fiap.com.br
%dev.app.ses.sender-email=noreply@fiap.com.br
